import argparse
import math
import sys
from pathlib import Path
from typing import Dict, Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from configs.config import SimulationConfig
from core.estimator import StateEstimator
from environment.map_manager import MapManager
from environment.wind_models import WindModelFactory


# =========================
# Configurable experiment knobs
# =========================
HEIGHT_AGL_M = 50.0
TIME_S = 600.0
OUTPUT_DIR = PROJECT_ROOT / "results" / "exp2_riskfield_analysis"
# The current project's risk surrogate is generated by an exponential mapping and
# remains numerically very small under the default configuration. A fixed threshold
# of 1e-6 is therefore more informative than 0.7 for identifying the top-risk cells.
HIGH_RISK_THRESHOLD = 1e-6
TKE_CURVE_MAX = 30.0
TKE_CURVE_POINTS = 600

FIG_DPI = 300
EDGE_MARGIN_M = 800.0
RIDGE_EXCLUDE_RADIUS_M = 400.0
LEEWARD_MIN_DOWNWIND_M = 400.0
LEEWARD_MAX_DOWNWIND_M = 2500.0
LEEWARD_MAX_CROSSWIND_M = 1600.0


def log(msg: str) -> None:
    print(f"[exp2] {msg}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Experiment 2: TKE and risk field analysis.")
    parser.add_argument(
        "--k-override",
        type=float,
        default=None,
        help="Override config.drone_robustness_K for risk-indicator mapping.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Custom output directory for this run.",
    )
    parser.add_argument(
        "--high-risk-threshold",
        type=float,
        default=HIGH_RISK_THRESHOLD,
        help="Threshold used to compute high_risk_ratio.",
    )
    return parser.parse_args()


def resolve_output_dir(custom_output_dir: Optional[str], k_override: Optional[float]) -> Path:
    if custom_output_dir:
        output_dir = Path(custom_output_dir)
        if not output_dir.is_absolute():
            output_dir = PROJECT_ROOT / output_dir
        return output_dir
    if k_override is None:
        return OUTPUT_DIR
    return PROJECT_ROOT / "results" / f"exp2_riskfield_analysis_k{int(round(k_override))}"


def build_environment_from_config(k_override: Optional[float] = None) -> Tuple[SimulationConfig, MapManager, object, StateEstimator]:
    log("正在加载地图与配置")
    config = SimulationConfig()
    config.noise_level = 0.0
    config.enable_single_agent_gusts = False
    config.enable_random_gusts = False
    if k_override is not None:
        config.drone_robustness_K = float(k_override)

    map_manager = MapManager(config)
    log("正在构建完整风场模型")
    wind_model = WindModelFactory.create(config.wind_model_type, config, bounds=map_manager.get_bounds())
    estimator = StateEstimator(map_manager, wind_model, config)
    return config, map_manager, wind_model, estimator


def compute_tke_field(
    config: SimulationConfig,
    map_manager: MapManager,
    estimator: StateEstimator,
) -> np.ndarray:
    log("正在计算 TKE 场")
    tke_field = np.zeros_like(map_manager.dem, dtype=float)
    z_abs = map_manager.dem + HEIGHT_AGL_M

    flat_x = map_manager.X.ravel()
    flat_y = map_manager.Y.ravel()
    flat_z = z_abs.ravel()

    tke_flat = np.zeros_like(flat_x, dtype=float)
    for idx, (xv, yv, zv) in enumerate(zip(flat_x, flat_y, flat_z)):
        tke_flat[idx] = estimator.get_tke(float(xv), float(yv), float(zv), t_s=TIME_S)

    tke_field[:, :] = tke_flat.reshape(map_manager.dem.shape)
    return tke_field


def compute_risk_indicator_field(
    config: SimulationConfig,
    map_manager: MapManager,
    tke_field: np.ndarray,
) -> np.ndarray:
    """
    Risk indicator uses the same exponential mapping as StateEstimator.get_risk(...),
    but is reported only as a turbulence-induced relative risk surrogate.
    """
    log("正在计算风险指标场")
    v_eff = max(float(config.cruise_speed_mps), 1.0)
    exposure_time = float(map_manager.resolution) / v_eff
    n0 = float(config.drone_response_freq_N0)
    k_robust = float(config.drone_robustness_K)

    safe_tke = np.maximum(tke_field, 1e-6)
    exponent = -n0 * exposure_time * np.exp(-k_robust / safe_tke)
    risk_indicator_field = 1.0 - np.exp(exponent)
    return np.clip(risk_indicator_field, 0.0, 1.0)


def compute_distribution_stats(field: np.ndarray, prefix: str) -> Dict[str, float]:
    vals = field[np.isfinite(field)]
    return {
        f"{prefix}_min": float(np.min(vals)),
        f"{prefix}_mean": float(np.mean(vals)),
        f"{prefix}_median": float(np.median(vals)),
        f"{prefix}_p95": float(np.percentile(vals, 95)),
        f"{prefix}_p99": float(np.percentile(vals, 99)),
        f"{prefix}_max": float(np.max(vals)),
    }


def _get_background_wind_unit(wind_model, config: SimulationConfig) -> np.ndarray:
    if hasattr(wind_model, "_get_time_varying_background_wind"):
        u_bg, v_bg = wind_model._get_time_varying_background_wind(TIME_S)
    else:
        u_bg, v_bg = config.env_wind_u, config.env_wind_v
    vec = np.array([float(u_bg), float(v_bg)], dtype=float)
    norm = np.linalg.norm(vec)
    if norm < 1e-9:
        return np.array([1.0, 0.0], dtype=float)
    return vec / norm


def _pick_point_from_mask(
    x_grid: np.ndarray,
    y_grid: np.ndarray,
    score: np.ndarray,
    mask: np.ndarray,
) -> Tuple[float, float]:
    masked_score = np.where(mask, score, -np.inf)
    if not np.isfinite(masked_score).any():
        raise ValueError("No valid candidate point found.")
    idx = int(np.nanargmax(masked_score))
    iy, ix = np.unravel_index(idx, score.shape)
    return float(x_grid[iy, ix]), float(y_grid[iy, ix])


def select_typical_points(
    config: SimulationConfig,
    map_manager: MapManager,
    wind_model,
    tke_field: np.ndarray,
    risk_indicator_field: np.ndarray,
) -> Dict[str, Tuple[float, float]]:
    log("正在选择典型区域点")
    dem = map_manager.dem
    slope = np.hypot(map_manager.grad_x, map_manager.grad_y)
    x_grid = map_manager.X
    y_grid = map_manager.Y
    min_x, max_x, min_y, max_y = map_manager.get_bounds()
    interior_mask = (
        (x_grid >= min_x + EDGE_MARGIN_M)
        & (x_grid <= max_x - EDGE_MARGIN_M)
        & (y_grid >= min_y + EDGE_MARGIN_M)
        & (y_grid <= max_y - EDGE_MARGIN_M)
    )

    dem_high = np.percentile(dem, 80)
    slope_high = np.percentile(slope, 75)
    ridge_mask = (dem >= dem_high) & (slope >= slope_high) & interior_mask
    ridge_score = dem + 400.0 * slope + 50.0 * risk_indicator_field
    ridge_point = _pick_point_from_mask(x_grid, y_grid, ridge_score, ridge_mask)

    ridge_xy = np.array(ridge_point, dtype=float)
    dist_from_ridge = np.hypot(x_grid - ridge_xy[0], y_grid - ridge_xy[1])

    dem_low = np.percentile(dem, 30)
    slope_low = np.percentile(slope, 35)
    valley_mask = (
        (dem <= dem_low)
        & (slope <= slope_low)
        & (dist_from_ridge >= RIDGE_EXCLUDE_RADIUS_M)
        & interior_mask
    )
    valley_score = -dem - 200.0 * slope - 20.0 * risk_indicator_field
    gentle_or_valley_point = _pick_point_from_mask(x_grid, y_grid, valley_score, valley_mask)

    wind_unit = _get_background_wind_unit(wind_model, config)
    rel_x = x_grid - ridge_xy[0]
    rel_y = y_grid - ridge_xy[1]
    downwind_dist = rel_x * wind_unit[0] + rel_y * wind_unit[1]
    crosswind_dist = np.abs(rel_x * (-wind_unit[1]) + rel_y * wind_unit[0])

    leeward_mask = (
        (downwind_dist >= LEEWARD_MIN_DOWNWIND_M)
        & (downwind_dist <= LEEWARD_MAX_DOWNWIND_M)
        & (crosswind_dist <= LEEWARD_MAX_CROSSWIND_M)
        & (slope >= np.percentile(slope, 50))
        & (risk_indicator_field >= np.percentile(risk_indicator_field, 75))
        & interior_mask
    )
    leeward_score = risk_indicator_field + 0.08 * slope + 0.00005 * downwind_dist
    try:
        leeward_point = _pick_point_from_mask(x_grid, y_grid, leeward_score, leeward_mask)
    except ValueError:
        fallback_mask = (
            (risk_indicator_field >= np.percentile(risk_indicator_field, 85))
            & (dist_from_ridge >= RIDGE_EXCLUDE_RADIUS_M)
            & interior_mask
        )
        leeward_point = _pick_point_from_mask(x_grid, y_grid, risk_indicator_field, fallback_mask)

    return {
        "ridge_point": ridge_point,
        "leeward_point": leeward_point,
        "gentle_or_valley_point": gentle_or_valley_point,
    }


def plot_tke_and_risk_fields(
    map_manager: MapManager,
    tke_field: np.ndarray,
    risk_indicator_field: np.ndarray,
    points: Dict[str, Tuple[float, float]],
    output_path: Path,
) -> None:
    log("正在绘制热力图")
    extent = [map_manager.x[0], map_manager.x[-1], map_manager.y[0], map_manager.y[-1]]

    point_specs = {
        "ridge_point": {"label": "Ridge", "marker": "^", "color": "#F94144"},
        "leeward_point": {"label": "Leeward", "marker": "s", "color": "#F8961E"},
        "gentle_or_valley_point": {"label": "Valley / Gentle", "marker": "o", "color": "#277DA1"},
    }

    fig, axes = plt.subplots(1, 2, figsize=(18, 8), constrained_layout=True)
    dem_contour_levels = np.linspace(np.min(map_manager.dem), np.max(map_manager.dem), 12)

    panels = [
        ("TKE Field", tke_field, "m$^2$/s$^2$", "magma"),
        ("Risk Indicator Field", risk_indicator_field, "Relative Risk Indicator", "turbo"),
    ]

    for ax, (title, field, cbar_label, cmap) in zip(axes, panels):
        base = ax.imshow(
            field,
            extent=extent,
            origin="lower",
            cmap=cmap,
            alpha=0.9,
        )
        ax.contour(
            map_manager.X,
            map_manager.Y,
            map_manager.dem,
            levels=dem_contour_levels,
            colors="white",
            linewidths=0.55,
            alpha=0.55,
        )

        for key, (px, py) in points.items():
            spec = point_specs[key]
            ax.scatter(px, py, s=80, marker=spec["marker"], color=spec["color"], edgecolors="black", zorder=5)
            ax.text(
                px + 180.0,
                py + 180.0,
                spec["label"],
                fontsize=10,
                color="black",
                bbox={"facecolor": "white", "alpha": 0.75, "edgecolor": "none", "pad": 1.5},
            )

        cbar = fig.colorbar(base, ax=ax, fraction=0.046, pad=0.03)
        cbar.set_label(cbar_label)
        ax.set_title(title, fontsize=14, fontweight="bold")
        ax.set_xlabel("X (m)")
        ax.set_ylabel("Y (m)")

    fig.suptitle(
        f"TKE and Turbulence-Induced Risk Indicator at {HEIGHT_AGL_M:.0f} m AGL, t = {TIME_S:.1f} s",
        fontsize=16,
    )
    fig.savefig(output_path, dpi=FIG_DPI, bbox_inches="tight")
    plt.close(fig)


def export_risk_summary_csv(
    config: SimulationConfig,
    map_manager: MapManager,
    tke_field: np.ndarray,
    risk_indicator_field: np.ndarray,
    high_risk_threshold: float,
    output_path: Path,
) -> None:
    log("正在导出统计指标")
    valid_mask = np.isfinite(tke_field) & np.isfinite(risk_indicator_field)
    slope = np.hypot(map_manager.grad_x, map_manager.grad_y)

    mean_tke = float(np.mean(tke_field[valid_mask]))
    peak_tke = float(np.max(tke_field[valid_mask]))
    mean_risk = float(np.mean(risk_indicator_field[valid_mask]))
    peak_risk = float(np.max(risk_indicator_field[valid_mask]))
    high_risk_mask = valid_mask & (risk_indicator_field > high_risk_threshold)
    high_risk_ratio = float(np.sum(high_risk_mask) / max(np.sum(valid_mask), 1))

    high_slope_mask = slope >= np.percentile(slope[valid_mask], 75)
    overlap_ratio = float(np.sum(high_risk_mask & high_slope_mask) / max(np.sum(high_risk_mask), 1))

    row = {
        "mean_tke": mean_tke,
        "peak_tke": peak_tke,
        "mean_risk": mean_risk,
        "peak_risk": peak_risk,
        "high_risk_ratio": high_risk_ratio,
        "high_slope_high_risk_overlap_ratio": overlap_ratio,
        "high_risk_threshold": float(high_risk_threshold),
        "N0_used": float(config.drone_response_freq_N0),
        "K_used": float(config.drone_robustness_K),
        "height_agl_m": float(HEIGHT_AGL_M),
        "time_s": float(TIME_S),
    }
    row.update(compute_distribution_stats(tke_field, "tke"))
    row.update(compute_distribution_stats(risk_indicator_field, "risk"))
    summary_df = pd.DataFrame([row])
    summary_df.to_csv(output_path, index=False, encoding="utf-8-sig")


def export_typical_points_csv(
    points: Dict[str, Tuple[float, float]],
    output_path: Path,
) -> None:
    rows = []
    for key, (xv, yv) in points.items():
        rows.append({"point_type": key, "x_m": float(xv), "y_m": float(yv)})
    pd.DataFrame(rows).to_csv(output_path, index=False, encoding="utf-8-sig")


def plot_risk_mapping_diagnostic(
    config: SimulationConfig,
    map_manager: MapManager,
    tke_field: np.ndarray,
    risk_indicator_field: np.ndarray,
    output_path: Path,
) -> None:
    log("正在绘制风险映射诊断图")
    vals_tke = tke_field[np.isfinite(tke_field)]
    vals_risk = risk_indicator_field[np.isfinite(risk_indicator_field)]

    v_eff = max(float(config.cruise_speed_mps), 1.0)
    exposure_time = float(map_manager.resolution) / v_eff
    n0 = float(config.drone_response_freq_N0)
    k_robust = float(config.drone_robustness_K)

    tke_axis = np.linspace(0.01, TKE_CURVE_MAX, TKE_CURVE_POINTS)
    risk_axis = 1.0 - np.exp(-n0 * exposure_time * np.exp(-k_robust / np.maximum(tke_axis, 1e-6)))

    fig, axes = plt.subplots(1, 2, figsize=(14, 5.6), constrained_layout=True)

    axes[0].plot(tke_axis, risk_axis, color="#F94144", linewidth=2.4)
    axes[0].axvline(float(np.percentile(vals_tke, 95)), color="#277DA1", linestyle="--", linewidth=1.5, label="TKE p95")
    axes[0].axvline(float(np.max(vals_tke)), color="#577590", linestyle="--", linewidth=1.5, label="TKE max")
    axes[0].set_title("TKE to Risk Mapping", fontsize=13, fontweight="bold")
    axes[0].set_xlabel("TKE")
    axes[0].set_ylabel("Risk Indicator")
    axes[0].grid(True, linestyle="--", alpha=0.35)
    axes[0].legend(loc="best")

    axes[1].hist(vals_tke, bins=60, alpha=0.65, color="#277DA1", label="TKE")
    axes[1].set_title("TKE Distribution", fontsize=13, fontweight="bold")
    axes[1].set_xlabel("TKE")
    axes[1].set_ylabel("Cell Count")
    axes[1].grid(True, linestyle="--", alpha=0.35)

    ax2 = axes[1].twinx()
    positive_risk = vals_risk[vals_risk > 0]
    if positive_risk.size > 0:
        ax2.hist(
            positive_risk,
            bins=50,
            alpha=0.35,
            color="#F3722C",
            label="Risk > 0",
            log=True,
        )
        ax2.set_yscale("log")
    ax2.set_ylabel("Risk Cell Count (log)")

    handles1, labels1 = axes[1].get_legend_handles_labels()
    handles2, labels2 = ax2.get_legend_handles_labels()
    axes[1].legend(handles1 + handles2, labels1 + labels2, loc="upper right")

    fig.suptitle(
        f"Risk Mapping Diagnostic (N0={n0:.1f}, K={k_robust:.1f}, exposure={exposure_time:.2f}s)",
        fontsize=15,
    )
    fig.savefig(output_path, dpi=FIG_DPI, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    output_dir = resolve_output_dir(args.output_dir, args.k_override)
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.k_override is not None:
        log(f"使用 K 重标定值: {args.k_override:.1f}")
    log(f"高风险阈值: {args.high_risk_threshold:.3e}")

    config, map_manager, wind_model, estimator = build_environment_from_config(args.k_override)
    tke_field = compute_tke_field(config, map_manager, estimator)
    risk_indicator_field = compute_risk_indicator_field(config, map_manager, tke_field)
    points = select_typical_points(config, map_manager, wind_model, tke_field, risk_indicator_field)

    figure_path = output_dir / "exp2_riskfield_analysis.png"
    summary_path = output_dir / "exp2_risk_summary.csv"
    points_path = output_dir / "exp2_typical_points.csv"
    diagnostic_path = output_dir / "exp2_risk_mapping_diagnostic.png"

    plot_tke_and_risk_fields(map_manager, tke_field, risk_indicator_field, points, figure_path)
    export_risk_summary_csv(
        config,
        map_manager,
        tke_field,
        risk_indicator_field,
        args.high_risk_threshold,
        summary_path,
    )
    export_typical_points_csv(points, points_path)
    plot_risk_mapping_diagnostic(config, map_manager, tke_field, risk_indicator_field, diagnostic_path)

    log(f"输出文件路径: {output_dir}")
    log(f"  - {figure_path.name}")
    log(f"  - {summary_path.name}")
    log(f"  - {points_path.name}")
    log(f"  - {diagnostic_path.name}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        log(f"实验失败: {exc}")
        raise
